
# pcd dir
pcd_dir : "C:/Users/Yaroslav/PycharmProjects/PointCloud/SemanticKITTI-visualizer/src/example/pcd"
pcd_extension : ".bin"

# label dir
label_dir : "C:/Users/Yaroslav/PycharmProjects/PointCloud/SemanticKITTI-visualizer/src/example/label"
label_extension : ".label"

# this store the dataset config
dataset_cfg_path : "C:/Users/Yaroslav/PycharmProjects/PointCloud/SemanticKITTI-visualizer/src/config/semantic-kitti.yaml"


# this store the viewpoint initialization config, which can copy from open3d GUI (json file) to modify initialization of the viewpoint
viewpoint_cfg_path : "C:/Users/Yaroslav/PycharmProjects/PointCloud/SemanticKITTI-visualizer/src/config/viewpoint.json"

# left top point position of GUI
position : 
  left : 300
  top : 100
  width : 1400
  height : 800

# open3d pcd point size
point_size : 1
